version: '3.8'
services:
  drupal:
    image: drupal:latest
    container_name: drupal
    ports:
      - 81:80
    volumes:
      - volumenDocker:/drupal_data

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - volumenDocker:/var/lib/mysql

volumes:
  volumenDocker:
